sa-token.token-prefix=Bearer
sa-token.token-style=simple-uuid
sa-token.token-name=Authorization

sa-token.alone-redis.database=0
sa-token.alone-redis.host=${spring.data.redis.host}
sa-token.alone-redis.port=${spring.data.redis.port}
sa-token.alone-redis.password=${spring.data.redis.password}
sa-token.alone-redis.timeout=10s

satori.white-uri=/favicon.ico,/v3/**,/swagger-ui/**,/*.html,/*.js,/*.css,/webjars/**
