spring.data.redis.timeout=5000
spring.data.redis.connect-timeout=10000
spring.data.redis.client-name=${spring.application.name}
spring.data.redisson.singleServerConfig.address=redis://${spring.data.redis.host}:${spring.data.redis.port}
spring.data.redisson.singleServerConfig.password=${spring.data.redis.password}
spring.data.redisson.singleServerConfig.subscriptionConnectionMinimumIdleSize=1
spring.data.redisson.singleServerConfig.subscriptionConnectionPoolSize=32
spring.data.redisson.singleServerConfig.connectionMinimumIdleSize=8
spring.data.redisson.singleServerConfig.connectionPoolSize=24